### PR TITLE
ExperimentB fixes

### PR DESCRIPTION
**Pull request by sbesson**
- Do not use the protein name to group different experiments since image filenames are duplicate
- Fix path issues with `20170907-08` folder

### CODE REVIEW

**Comment by sbesson** [comment]
These have been re-used for the re-import of `idr0052-walther-condensinmap/experimentB` on `test61`

screen shot 2019-02-11 at 19 59 31

Functionally this works. Opinions welcome on unifying the naming scheme of the datasets across the three experiments. Would it make sense to have each dataset/assay contain 1- the protein of interest and 2- the date of acquisition. If so:

- should the date or the protein be listed first?
- which format should be used for the dates. [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) is probably a good representation although I am not sure there is a short way to represent a range (e.g. `20170907-08`)

/cc @francesw @manics

**Comment by sbesson** [comment]
Re-import using the last change gives the following structure

screen shot 2019-02-13 at 09 07 01

@francesw: any last thoughts against using this for `experimentA` and `experimentB`? `experimentC` will probably only use the protein name e.g. `NCAPD2` or `NCAPH2 NCAPH` for the double STED experiment.

**Comment by francesw** [comment]
Happy to go with this structure, it is clear to understand.  Only comments are dates have been represented differently for previous studies (YYMMDD) and underscores have been used instead of spaces (e.g. idr0001).

**Comment by sbesson** [comment]
Agreed about the date discrepancy across studies. I vote for using [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) whenever possible moving forward as it reduces ambiguity in the interpretation. In terms of interoperability, it also matches the OME specification for the [Acquisition Date](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Image_AcquisitionDate).

Re using spaces vs underscores in dataset names, I am still unsure of the potential implications especially in terms of the new searching functionalities. I think underscore 1- should work and 2- might be the safest choice. I can push another change to switch to this representation and compare.

**Comment by sbesson** [comment]
Merging as per https://github.com/IDR/idr0052-walther-condensinmap/pull/3#issuecomment-463124016, I will apply the same layout changes to `experimentA` and `experimentC` in a follow-up so that all experiments can be reviewed side by side.

**Pull request merged**
